# Generated by Django 4.2.4 on 2023-08-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_add_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
