# Generated by Django 4.0 on 2022-07-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='user',
            new_name='artist',
        ),
    ]
