# Generated by Django 4.0 on 2022-07-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='user',
            new_name='cust',
        ),
    ]
