# Generated by Django 4.0.1 on 2022-07-29 14:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_rename_user_artist_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
